variables:
  API_TOKEN: $SWA_CLI_DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/DocConnect'

preview:
  stage: deploy
  image : node:lts-bullseye
  tags:
    - docker-linux
  script:
    - cd $APP_PATH
    - npm ci
    - npm run build
    - npm install -g @azure/static-web-apps-cli
    - swa deploy --verbose=silly ./dist -d $API_TOKEN -w ./
    - echo "Done"
  only:
    - merge_requests

deploy:
  stage: deploy
  image : node:lts-bullseye
  tags:
    - docker-linux
  script:
    - cd $APP_PATH
    - npm ci
    - npm run build
    - npm install -g @azure/static-web-apps-cli
    - swa deploy --verbose=silly ./dist -d $API_TOKEN -w ./ --env production
    - echo "Done"
  only:
    - test
